In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pybisp
import sys
import pandas as pd

In [2]:
sys.path.append('/Users/rsingh/Dropbox/repos//iiscer-kolkata-traps-bubbles/WorkTree/data/')
data = pd.ExcelFile('/Users/rsingh/Dropbox/repos/iiscer-kolkata-traps-bubbles/WorkTree/data/water_calibrated_brownian.xlsx').parse()
N_exp = data.size
x_experiment = data['Data(micron)'].values
dt_exp = (1./1500)

In [3]:
oup = pybisp.oup.Inference(x_experiment, dt_exp)
#oup.logProb(252.3, 0.17)

In [4]:
#plt.plot(x_experiment)

In [5]:
oup.mapEstimate()

lambda= 230.035251638  D= -0.167003485887  k= -1377.42784479 l/D -1377.42784479


(230.03525163816849, -0.16700348588685224, -1377.427844793739)

In [6]:
0.0010565853105169627 / 0.00010223788961696377

10.334576686544294

In [7]:
x = np.linspace(0, 10,11)

In [31]:
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [32]:
x[1:]

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [33]:
x[:-1]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])